async function request<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,init);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof d?.error==="string"?d.error:`Request failed (${r.status})`);return d as T;}
async function authHeaders():Promise<Record<string,string>>{const{getAuth}=await import("firebase/auth"),{firebaseApp}=await import("./firebase");let u=getAuth(firebaseApp).currentUser;if(!u){const{getWyBlogUser}=await import("./cloud");try{u=await getWyBlogUser();}catch(e){throw new Error(e instanceof Error?`Sign-in failed: ${e.message}`:"Sign-in failed.");}}if(!u)throw new Error("Sign-in failed: no user session was returned.");return{Authorization:`Bearer ${await u.getIdToken()}`};}
export async function connectBlogger(){const d=await request<{authorizationUrl:string}>("/api/auth/google",{method:"POST",headers:await authHeaders()});if(!d.authorizationUrl)throw new Error("Google authorization URL was not returned.");window.location.assign(d.authorizationUrl);}
export async function getConnectionStatus():Promise<{connected:boolean;blogId?:string;blogName?:string;blogUrl?:string;accountEmail?:string;accountName?:string}>{return request("/api/auth/status",{headers:await authHeaders()});}
export async function getBillingStatus():Promise<{plan:"free"|"pro";status:string;activeUntil:string|null}>{return request("/api/billing/status",{headers:await authHeaders()});}
export async function getBillingConfig():Promise<{usd:number;ngn:number;environment:string;encryptionKey:string}>{return request("/api/billing/config");}
export async function startProCheckout(payload:{currency:"USD"|"NGN";name:string;email:string;payment_method:{type:"card";card:{nonce:string;encrypted_card_number:string;encrypted_expiry_month:string;encrypted_expiry_year:string;encrypted_cvv:string}}}){return request<{reference:string;chargeId:string;status:string;nextAction?:any;authorization?:any}>("/api/billing/create",{method:"POST",headers:{"Content-Type":"application/json",...(await authHeaders())},body:JSON.stringify(payload)});}
export async function verifyProPayment(reference:string){return request<{plan:"free"|"pro";status:string;activeUntil?:string;nextAction?:any}>("/api/billing/verify",{method:"POST",headers:{"Content-Type":"application/json",...(await authHeaders())},body:JSON.stringify({reference})});}
export async function authorizeProPayment(reference:string,chargeId:string,authorization:any):Promise<{status?:string;nextAction?:any;authorization?:any}>{return request<{status?:string;nextAction?:any;authorization?:any}>("/api/billing/authorize",{method:"POST",headers:{"Content-Type":"application/json",...(await authHeaders())},body:JSON.stringify({reference,chargeId,authorization})});}
export async function getBlogPosts():Promise<{posts:any[]}>{return request("/api/posts",{headers:await authHeaders()});}
export async function getBlogPages():Promise<{pages:any[]}>{return request("/api/pages",{headers:await authHeaders()});}
export async function saveBloggerPage(payload:{id?:string;title:string;content:string;published?:boolean}):Promise<{page?:any;url?:string}>{return request("/api/pages",{method:"POST",headers:{"Content-Type":"application/json",...(await authHeaders())},body:JSON.stringify(payload)});}
export async function deleteBloggerPage(id:string):Promise<{ok:boolean}>{return request(`/api/pages/${encodeURIComponent(id)}`,{method:"DELETE",headers:await authHeaders()});}
export async function saveBloggerPost(payload:{id?:string;title:string;content:string;labels:string[];published?:boolean}):Promise<{post?:any;url?:string}>{return request("/api/posts",{method:"POST",headers:{"Content-Type":"application/json",...(await authHeaders())},body:JSON.stringify(payload)});}
export async function runDiagnosis():Promise<{diagnosis?:any;cached?:boolean;model?:string}>{return request("/api/diagnosis",{method:"POST",headers:{"Content-Type":"application/json",...(await authHeaders())}});}
export async function generateSEOSuggestions(){return request<{generated?:boolean;count?:number;model?:string}>("/api/seo/suggestions",{method:"POST",headers:{"Content-Type":"application/json",...(await authHeaders())}});}
export async function registerPushToken(token:string){return request("/api/push",{method:"POST",headers:{"Content-Type":"application/json",...(await authHeaders())},body:JSON.stringify({token})});}
export async function saveBackupToDrive(){throw new Error("Google Drive backup is not configured in this WyBlog build; no backup was claimed.");}
export async function uploadMediaToDrive(){throw new Error("Google Drive media upload is not configured in this WyBlog build; no upload was claimed.");}
