import type { Plugin } from "./types";

const targetByName: Record<string, Plugin["integrationTarget"]> = {
  "SEO Toolkit":"theme", "Table of Contents":"article-start", "Related Posts":"article-end", "Reading Progress":"theme", "Dark Mode":"theme",
  "Social Share":"article-start", "Push Notifications":"server", "Analytics":"server", "Schema & Structured Data":"theme",
  "Meta Title & Description":"editor", "Open Graph & Social Cards":"theme", "XML Sitemap Monitor":"server", "Robots.txt Checker":"server",
  "Image Alt Text":"editor", "Internal Link Assistant":"editor", "PageSpeed Insights":"server", "Core Web Vitals Monitor":"server",
  "Google Search Console":"server", "Redirect & URL Audit":"server", "Advanced Push":"server", "AI SEO":"editor",
  "Keyword & Topic Planner":"editor", "FAQ Schema Builder":"article-end", "Breadcrumbs":"theme", "Copy Code Button":"article-end",
  "Reading Time":"article-start", "Print Article":"article-start", "Estimated Reading Progress":"theme", "Content Freshness Badge":"article-start",
  "Cookie/Consent Link":"article-end", "Newsletter CTA":"article-end", "404 Recovery Links":"theme", "Lazy Image Helper":"article-end"
};
const base = (name:string, description:string, category:string, snippet:string, instructions:string[], extra:Partial<Plugin>={}): Plugin => ({id:name.toLowerCase().replace(/[^a-z0-9]+/g,"-"), name, description, category, snippet, instructions, ...(targetByName[name] ? { integrationTarget: targetByName[name] } : {}), ...extra});

export const plugins: Plugin[] = [
  base("SEO Toolkit", "Site-wide SEO checks, metadata helpers and health insights.", "SEO", `<!-- WyBlog SEO Toolkit: paste this inside Blogger Theme > Edit HTML, before </head> -->\n<meta name="robots" content="index,follow,max-image-preview:large">\n<meta name="viewport" content="width=device-width,initial-scale=1">`, ["Back up your Blogger theme first.", "Open Blogger → Theme → Edit HTML.", "Paste immediately before </head>.", "Save and verify a public post." ]),
  base("Table of Contents", "Generate clean in-post navigation for long articles.", "Content", `<nav class="wyblog-toc" aria-label="Table of contents"><strong>Table of contents</strong><ol id="wyblog-toc-list"></ol></nav>\n<script>(function(){const root=document.querySelector('.post-body');const list=document.getElementById('wyblog-toc-list');if(!root||!list)return;root.querySelectorAll('h2,h3').forEach((h,i)=>{h.id=h.id||'wyblog-heading-'+(i+1);const li=document.createElement('li');li.innerHTML='<a href="#'+h.id+'">'+h.textContent+'</a>';list.appendChild(li)})})();</script>`, ["Open Blogger → Theme → Edit HTML.", "Place the block where the table of contents should appear.", "Save and test a post containing H2/H3 headings." ]),
  base("Related Posts", "Add contextual related-post links using Blogger's public feed.", "Content", `<div class="wyblog-related" aria-label="Related posts"><strong>Related posts</strong><ul data-wyblog-related-list></ul></div>
<script>(function(){const box=document.querySelector(".wyblog-related"),list=box?.querySelector("[data-wyblog-related-list]");if(!box||!list)return;fetch("/feeds/posts/default?alt=json&max-results=8").then(r=>r.ok?r.json():Promise.reject()).then(data=>{const current=location.href;const items=(data.feed?.entry||[]).filter(e=>!e.link?.some(l=>l.rel==="alternate"&&l.href===current)).slice(0,5);items.forEach(e=>{const href=e.link?.find(l=>l.rel==="alternate")?.href;if(!href)return;const li=document.createElement("li"),a=document.createElement("a");a.href=href;a.textContent=e.title?.$t||"Related post";li.appendChild(a);list.appendChild(li)});if(!list.children.length)box.remove()}).catch(()=>box.remove())})();</script>`, ["Place the complete block after the post body.", "It reads the public Blogger posts feed on the same blog; no private API key is required.", "If the public feed is unavailable, the widget removes itself instead of showing an endless loading state.", "Publish a test post and confirm related links render."]),
  base("Reading Progress", "Show a lightweight progress indicator on articles.", "UX", `<div id="wyblog-progress" style="position:fixed;top:0;left:0;width:0;height:3px;background:#111;z-index:99999"></div>\n<script>(function(){const bar=document.getElementById('wyblog-progress');addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;bar.style.width=(max>0?(scrollY/max)*100:0)+'%'},{passive:true})})();</script>`, ["Open Blogger → Theme → Edit HTML.", "Paste before </body>.", "Save and scroll through a public post to test." ]),
  base("Dark Mode", "Give visitors a comfortable dark reading option.", "UX", `<button id="wyblog-dark" type="button" aria-label="Toggle dark mode">Dark mode</button>\n<style>body.wyblog-dark{background:#111!important;color:#eee!important}body.wyblog-dark a{color:#9ecbff!important}</style>\n<script>document.getElementById('wyblog-dark')?.addEventListener('click',()=>document.body.classList.toggle('wyblog-dark'));</script>`, ["Paste the block where the toggle should appear.", "Adjust selectors for your Blogger theme if necessary.", "Save and test on mobile and desktop." ]),
  base("Social Share", "Add compact share actions to posts.", "Growth", `<button type="button" onclick="navigator.share?navigator.share({title:document.title,url:location.href}):navigator.clipboard.writeText(location.href)">Share</button>`, ["Place near the post title or footer.", "The fallback copies the page URL when Web Share is unavailable.", "Test on a phone and desktop browser." ]),
  base("Push Notifications", "Notify subscribers when new posts are published.", "Growth", `<!-- Client registration belongs on your HTTPS site; server delivery must use Firebase Admin. -->\n<script>console.info('Configure FCM on your trusted server.');</script>`, ["Enable Firebase Cloud Messaging.", "Serve the site over HTTPS and configure the messaging service worker.", "Generate a Web Push VAPID key in Firebase Console.", "Store tokens server-side and send through Firebase Admin; never expose an Admin key." ]),
  base("Analytics", "Bring useful blog performance signals into WyBlog.", "Analytics", `<!-- Use only a provider-approved public measurement ID. -->\n<script>console.info('Add your public analytics measurement ID through the supported integration.');</script>`, ["Choose an analytics provider.", "Add only the public measurement ID.", "Publish and verify events in the provider dashboard." ]),
  base("Schema & Structured Data", "Check article structure and generate schema recommendations.", "SEO", `<!-- Review generated JSON-LD in WyBlog, then paste the approved block into Blogger Theme → Edit HTML. -->`, ["Run a connected-site diagnosis.", "Review the recommended Article/Breadcrumb JSON-LD.", "Paste approved JSON-LD before </head>.", "Validate the public page after publishing."]),
  base("Meta Title & Description", "Check title and description length before publishing.", "SEO", `<!-- No theme code is required; use WyBlog's editor SEO fields. -->`, ["Open an article in WyBlog.", "Set SEO title and meta description.", "Keep the description concise and unique.", "Publish and inspect the public page."]),
  base("Open Graph & Social Cards", "Check social title, description and image metadata.", "SEO", `<!-- Add the generated Open Graph tags to Blogger Theme → Edit HTML. -->`, ["Run a connected audit.", "Copy the recommended OG tags.", "Paste them before </head>.", "Share a public URL and confirm the card preview."]),
  base("XML Sitemap Monitor", "Check sitemap availability and discoverability.", "SEO", `<!-- No theme code required. WyBlog checks the public sitemap endpoint. -->`, ["Connect Blogger.", "Open the sitemap monitor.", "Confirm the public sitemap responds successfully.", "Submit or resubmit it in your search platform if needed."]),
  base("Robots.txt Checker", "Inspect robots directives and accidental blocking.", "SEO", `<!-- No theme code required. WyBlog checks the public robots.txt response. -->`, ["Connect Blogger.", "Run the robots check.", "Review Disallow directives.", "Remove accidental blocking in Blogger settings."]),
  base("Image Alt Text", "Find missing or weak image alternative text.", "Accessibility", `<!-- No theme code required. Audit your post HTML and add descriptive alt text. -->`, ["Run a diagnosis.", "Open affected posts.", "Add concise descriptive alt text to meaningful images.", "Leave decorative images empty when appropriate."]),
  base("Internal Link Assistant", "Find orphaned content and useful internal-link opportunities.", "SEO", `<!-- Suggestions are generated by the WyBlog content scan. No secret code belongs in Blogger. -->`, ["Connect Blogger and scan posts.", "Review suggested internal links.", "Add relevant links in the WyBlog editor.", "Republish and rerun the scan."]),
  base("PageSpeed Insights", "Run public-page performance checks without exposing API secrets.", "Performance", `<!-- PageSpeed requests run server-side when configured. No secret key belongs in Blogger. -->`, ["Connect your public blog.", "Choose a public page URL.", "Run a mobile or desktop performance test.", "Apply safe recommendations and rerun the test."]),
  base("Core Web Vitals Monitor", "Track LCP, INP and CLS when a supported source is configured.", "Performance", `<!-- Field/lab data integration runs through the WyBlog server. -->`, ["Activate Pro.", "Configure the supported performance source on the server.", "Measure a public page.", "Review LCP, INP and CLS and optimize the theme/content."]),
  base("Google Search Console", "Connect indexing and search-performance data.", "Integration", `<!-- OAuth connection; never paste private Google credentials into Blogger. -->`, ["Activate Pro.", "Connect a Google account with property access.", "Select the matching Blogger property.", "Sync and review search/indexing data."]),
  base("Redirect & URL Audit", "Find changed URLs, redirect chains and broken destinations.", "SEO", `<!-- URL auditing runs server-side; no Blogger theme code is required. -->`, ["Activate Pro.", "Connect Blogger and run the audit.", "Review redirects and broken destinations.", "Fix URLs and rerun the audit."]),
  base("Advanced Push", "Schedule notifications and segment subscribers.", "Growth", `<!-- Advanced Push is server-side; keep all Firebase Admin credentials private. -->`, ["Activate Pro.", "Configure Firebase Admin on the server.", "Create subscriber segments.", "Schedule sends and review send/failure logs."]),
  base("AI SEO", "Turn deterministic SEO findings into concise action plans.", "AI", `<!-- AI SEO runs through WyBlog; no AI provider secret should be pasted into Blogger. -->`, ["Activate Pro.", "Connect Blogger and run diagnosis.", "Open AI SEO and review recommendations.", "Apply approved changes in the editor or Blogger theme."]),
  base("Keyword & Topic Planner", "Turn a draft topic into focused keyword and subtopic ideas.", "AI", `<!-- Planner runs inside WyBlog; it does not inject code into Blogger. -->`, ["Activate Pro.", "Enter a draft topic in the planner.", "Review suggested terms and subtopics.", "Use relevant terms naturally in the article."], {pro:true}),
  base("FAQ Schema Builder", "Create an FAQ JSON-LD block from your question-and-answer content.", "SEO", `<script type="application/ld+json">/* WyBlog generates this block from your approved FAQ entries. */</script>`, ["Activate Pro.", "Enter the exact visible FAQ questions and answers.", "Generate and review the JSON-LD.", "Paste it before </head> and keep the FAQ visible on the page."], {pro:true}),
  base("Breadcrumbs", "Add accessible breadcrumb navigation to Blogger posts.", "Navigation", `<nav aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true"> / </span><span>Current post</span></nav>`, ["Activate Pro.", "Paste the block in the post header area of Theme → Edit HTML.", "Replace the current-post placeholder with your theme's post title variable if needed.", "Test category/label navigation on mobile."], {pro:true}),
  base("Copy Code Button", "Add a one-tap copy button to code blocks in technical articles.", "Developer", `<button type="button" class="wyblog-copy-code">Copy code</button>\n<script>document.addEventListener('click',e=>{const b=e.target.closest('.wyblog-copy-code');if(!b)return;const code=b.parentElement?.querySelector('code');if(code)navigator.clipboard?.writeText(code.innerText);});</script>`, ["Activate Pro.", "Place the button beside a code block.", "Ensure each code block contains a <code> element.", "Test copy behavior on HTTPS."], {pro:true}),
  base("Reading Time", "Show an estimated reading time for each article.", "Content", `<span id="wyblog-reading-time" aria-label="Estimated reading time"></span>\n<script>(function(){const root=document.querySelector('.post-body');const out=document.getElementById('wyblog-reading-time');if(!root||!out)return;const words=(root.innerText||'').trim().split(/\\s+/).filter(Boolean).length;out.textContent=Math.max(1,Math.ceil(words/200))+' min read';})();</script>`, ["Place the block near the post title.", "Adjust the .post-body selector if your theme uses a different container.", "Publish and verify the estimate on a real article."]),
  base("Print Article", "Add a clean print action for readers who want a paper/PDF copy.", "Content", `<button type="button" onclick="window.print()">Print article</button>`, ["Place the button near your article actions.", "Add print CSS in your theme if you want to hide navigation/sidebar elements.", "Test the print preview before publishing."]),
  base("Estimated Reading Progress", "Show article reading progress with a lightweight top bar.", "UX", `<div id="wyblog-read-progress" aria-hidden="true" style="position:fixed;top:0;left:0;height:3px;width:0;background:#111;z-index:99999"></div>
<script>(function(){const bar=document.getElementById("wyblog-read-progress");if(!bar)return;const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;bar.style.width=(max>0?Math.min(100,Math.max(0,scrollY/max*100)):0)+"%"};addEventListener("scroll",update,{passive:true});addEventListener("resize",update,{passive:true});update();})();</script>`, ["Activate Pro.", "Place the complete block before </body> in Blogger Theme → Edit HTML.", "Save and test long and short posts on mobile.", "Keep the bar out of printable content if your print CSS needs it."], {pro:true}),
  base("Content Freshness Badge", "Show readers when an article was recently updated.", "Content", `<span class="wyblog-updated" data-updated="" aria-label="Updated date"></span>
<script>(function(){const out=document.querySelector(".wyblog-updated[data-updated]");const article=document.querySelector(".post-body");if(!out||!article)return;const time=article.querySelector("time[datetime]");if(time){const d=new Date(time.getAttribute("datetime")||"");if(!Number.isNaN(d.getTime()))out.textContent="Updated "+d.toLocaleDateString();}})();</script>`, ["Place the badge near the post date.", "Use a theme date element that exposes a valid datetime value.", "If no valid date exists, the badge stays empty rather than showing a fake date."]),
  base("Cookie/Consent Link", "Add a simple link to your privacy or consent policy.", "Compliance", `<a href="/p/privacy-policy.html" rel="nofollow">Privacy & cookie policy</a>`, ["Create or confirm your privacy policy page first.", "Update the href to the exact Blogger page URL.", "Place the link in the footer or navigation."]),
  base("Newsletter CTA", "Add a compact newsletter signup call-to-action without embedding private credentials.", "Growth", `<div class="wyblog-newsletter"><strong>Get new posts</strong><p>Subscribe through your chosen email provider.</p><a href="YOUR_PUBLIC_SIGNUP_URL" rel="nofollow noopener">Subscribe</a></div>`, ["Replace YOUR_PUBLIC_SIGNUP_URL with your provider's public signup URL.", "Do not paste an email-provider API key into Blogger.", "Test signup and unsubscribe links before publishing."]),
  base("404 Recovery Links", "Give visitors useful navigation when they land on a missing page.", "Navigation", `<section class="wyblog-404"><h2>Page not found</h2><p>Try the homepage or search.</p><a href="/">Go home</a></section>`, ["Place the block in your Blogger 404/error template if supported by your theme.", "Add your own search link if your theme has one.", "Test an intentionally invalid URL."]),
  base("Lazy Image Helper", "Improve image loading behavior with safe lazy-loading attributes.", "Performance", `<!-- Add loading="lazy" decoding="async" to non-critical Blogger images. -->`, ["Activate Pro.", "Apply loading=lazy only to below-the-fold images.", "Keep the main above-the-fold image eager when appropriate.", "Test layout stability after publishing."], {pro:true})
];

const proPluginNames = new Set(['SEO Toolkit', 'Table of Contents', 'Related Posts', 'Reading Progress', 'Dark Mode', 'Push Notifications', 'Analytics', 'Schema & Structured Data', 'Open Graph & Social Cards', 'PageSpeed Insights', 'Core Web Vitals Monitor', 'Google Search Console', 'Redirect & URL Audit', 'Advanced Push', 'AI SEO', 'Keyword & Topic Planner', 'FAQ Schema Builder', 'Breadcrumbs', 'Copy Code Button', 'Estimated Reading Progress', 'Lazy Image Helper']);
for (const plugin of plugins) {
  if (proPluginNames.has(plugin.name)) plugin.pro = true;
}

